# 应用配置文件 - 使用环境变量替换需要变动的部分
app:
  name: "{APP_NAME}"
  port: "{APP_PORT}"
  mode: "{APP_MODE}"
  log_level: "{LOG_LEVEL}"

oauth2:
  client_id: "{OAUTH2_CLIENT_ID}"
  client_secret: "{OAUTH2_CLIENT_SECRET}"
  redirect_uri: "{OAUTH2_REDIRECT_URI}"
  authorization_endpoint: "https://connect.linux.do/oauth2/authorize"
  token_endpoint: "https://connect.linux.do/oauth2/token"
  user_endpoint: "https://connect.linux.do/api/user"

log:
  level: "{LOG_LEVEL}"
  format: "{LOG_FORMAT}"
  output: "{LOG_OUTPUT}"
  file_path: "{LOG_FILE_PATH}"