# CDK分发平台配置文件

# 应用服务配置
app:
  name: "cdk-platform"
  env: "development" # development, testing, production
  debug: true
  port: 8080
  read_timeout: 10  # 秒
  write_timeout: 10  # 秒
  idle_timeout: 60  # 秒
  api_prefix: "/controller/v1"
  allow_cors: true
  cors_domains: ["http://localhost:3000", "https://admin.example.com"]
  jwt_secret: "your-jwt-secret-key" # 生产环境中应该使用更安全的方式存储
  jwt_ttl: 86400 # token有效期，单位秒

# LinuxDo OAuth2配置
oauth2:
  client_id: "{OAUTH2_CLIENT_ID}"
  client_secret: "{OAUTH2_CLIENT_SECRET}"
  redirect_uri: "{OAUTH2_REDIRECT_URI}"
  authorization_endpoint: "https://connect.linux.do/oauth2/authorize"
  token_endpoint: "https://connect.linux.do/oauth2/token"
  user_endpoint: "https://connect.linux.do/api/user"

# 数据库配置
database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "password"
  database: "cdk_platform"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600  # 秒
  log_level: "info"  # error, warn, info, debug, silent

# Redis配置
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 100
  min_idle_conns: 10
  dial_timeout: 5  # 秒
  read_timeout: 3  # 秒
  write_timeout: 3  # 秒
  max_retries: 3
  min_retry_backoff: 8  # 毫秒
  max_retry_backoff: 512  # 毫秒

# 日志配置
log:
  level: "debug"  # debug, info, warn, error, fatal, panic
  format: "json"  # text, json
  output: "stdout"  # stdout, file
  file_path: "./logs/app.log"
  max_size: 100  # MB
  max_age: 30  # 天
  max_backups: 10
  compress: true