definitions:
  health.HealthResponse:
    properties:
      data: {}
      error_msg:
        type: string
    type: object
  oauth.CallbackRequest:
    properties:
      code:
        type: string
      state:
        type: string
    type: object
  oauth.CallbackResponse:
    properties:
      data: {}
      error_msg:
        type: string
    type: object
  oauth.GetLoginURLResponse:
    properties:
      data:
        type: string
      error_msg:
        type: string
    type: object
info:
  contact: {}
  title: Linux Do CDK
paths:
  /api/v1/health:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/health.HealthResponse'
      tags:
      - health
  /api/v1/oauth/callback:
    post:
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/oauth.CallbackRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/oauth.CallbackResponse'
      tags:
      - oauth
  /api/v1/oauth/login:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/oauth.GetLoginURLResponse'
      tags:
      - oauth
swagger: "2.0"
