name: Go Build

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches:
      - "dev"
      - "main"

jobs:
  go_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build main.go
